### ISSUE TITLE
License

### ISSUE THREAD

**Issue by bcronje** [fredrikwidlund/libdynamic#1]
Is this library licensed under GPL or LGPL?

**Comment by fredrikwidlund** [comment]
Currently it is GPL without having given it much thought. Could probably go with LGPL instead. The point is making a useful library more than anything else. If you want to use it be aware that it is an early release and that the API is subject to change.

**Comment by bcronje** [comment]
Thanks for the response. I agree making a useful library should be priority 1. You should however give the license some thought though in my opinion. The viral nature of GPL means your library exposure and usage will be limited to only other GPL based projects. So unfortunately we will not even be able to even evaluate it.
Anyway, looks interesting and good luck.

**Comment by fredrikwidlund** [comment]
The library now uses LGPL.
